### PR TITLE
Use redis-module-sdk fix #26

### LINKED ISSUE #26: ft.add depreciated
Replace ft.add with HSET since it is depreciated.

See https://oss.redislabs.com/redisearch/Commands/#ftadd

https://github.com/danitseitlin/redis-modules-sdk/blob/master/.github/docs/doc.md#-redisearch-module
maybe change module

### PR DESCRIPTION
**Pull request by b3z**
Docs are sadly non existing. RTFC https://github.com/danitseitlin/redis-modules-sdk/blob/master/modules/redisearch.ts

### CODE REVIEW

**Comment by b3z** [comment]
await https://github.com/danitseitlin/redis-modules-sdk/issues/39

**Comment by b3z** [comment]
await https://github.com/danitseitlin/redis-modules-sdk/issues/39

**Comment by danitseitlin** [comment]
`Docs are sadly non existing. RTFC https://github.com/danitseitlin/redis-modules-sdk/blob/master/modules/redisearch.ts` - @b3z   I'm sorry you had hard time with understanding how to use things in the redis-modules-sdk package. I'm looking to improve that.
What kind of documentation are you looking for (or might be looking for in the future)?
Thanks!

**Comment by b3z** [comment]
Don't worry. It was okay. 

Firs thing was a typo.

The documentation you have is not very helpful but when you read the modules code things are getting clear pretty fast. Also because of the nice jdocs you wrote. 

If you want I can make a pr for RediSearch as an example how I would wish the documentation was. :)

Also I am not that experienced in typescript (as you may see in my project how I write code) so maybe I had a harder time than others.

**Comment by danitseitlin** [comment]
@b3z You are more than welcome to contribute! Feel free to add any helpful documentation or any code to my project! Thanks!

**Pull request merged**
